### ISSUE TITLE
errore dipendenze con react 18.2.0

### ISSUE THREAD

**Issue by ccampisano** [pagopa/mui-italia#416]
### Problem description
errore dipendenze con "react": "^18.2.0" e @mui/material": "^5.11.13"

### Steps to reproduce
eseguire il comando di installazione tema mui-italia in una app react 18.2.0:

![errore dipendenze](https://github.com/pagopa/mui-italia/assets/120666584/70a69c43-db59-4f2e-9902-0369605bb1d5)

### Expected behavior
il tema di mui-italia dovrebbe risultare installato ed utilizzabile, invece il comando restituisce errore

### Screenshots
vedere shot sopra 

### Environment
C:\...>npm version
{
  'sanpae2-fatturazione-attiva-fe': '0.1.0',
  npm: '8.1.2',
  node: '17.1.0',
  v8: '9.5.172.25-node.13',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '102',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '3.0.0+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

### Additional information
contenuto di package.json:
{
  "name": "sanpae2-fatturazione-attiva-fe",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@fontsource/roboto": "^4.5.8",
    "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.13",
    "@mui/x-date-pickers": "^6.0.2",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.3.4",
    "dayjs": "^1.11.7",
    "js-file-download": "^0.4.12",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.9.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by lucacavallaro** [comment]
Abbiamo rilasciato di recente la versione `1.0` di `mui-italia`, che è compatibile con React `18.x`.

https://github.com/pagopa/mui-italia/releases/tag/v1.0.0-RELEASE
